

class BodyChunksCatalog(object):

    NONE_ID = 0
    HEAD_ID = 1
    HEAD_CHEST_ID = 2
    HEAD_LEFT_ARM_ID = 3
    HEAD_LEFT_ARM_HAND_ID = 4
    HEAD_RIGHT_ARM_ID = 5
    HEAD_RIGHT_ARM_HAND_ID = 6
    HEAD_ARMS_ID = 7
    HEAD_ARMS_HANDS_ID = 8
    CENTER_ID = 9
    CENTER_HIPS_ID = 10
    CENTER_LEFT_LEG_ID = 11
    CENTER_LEFT_LEG_FOOT_ID = 12
    CENTER_RIGHT_LEG_ID = 13
    CENTER_RIGHT_LEG_FOOT_ID = 14
    CENTER_LEGS_ID = 15
    CENTER_LEGS_FEET_ID = 16
    WHOLE_BODY_ID = 17

    NONE_TAG = 'None'
    HEAD_TAG = 'Head'
    HEAD_CHEST_TAG = 'Head-Chest'
    HEAD_LEFT_ARM_TAG = 'Head-Left-Arm'
    HEAD_LEFT_ARM_HAND_TAG = 'Head-Left-Arm-Hand'
    HEAD_RIGHT_ARM_TAG = 'Head-Right-Arm'
    HEAD_RIGHT_ARM_HAND_TAG = 'Head-Right-Arm-Hand'
    HEAD_ARMS_TAG = 'Head-Arms'
    HEAD_ARMS_HANDS_TAG = 'Head-Arms-Hands'
    CENTER_TAG = 'Center'
    CENTER_HIPS_TAG = 'Center-Hips'
    CENTER_LEFT_LEG_TAG = 'Center-Left-Leg'
    CENTER_LEFT_LEG_FOOT_TAG = 'Center-Left-Leg-Foot'
    CENTER_RIGHT_LEG_TAG = 'Center-Right-Leg'
    CENTER_RIGHT_LEG_FOOT_TAG = 'Center-Right-Leg-Foot'
    CENTER_LEGS_TAG = 'Center-Legs'
    CENTER_LEGS_FEET_TAG = 'Center-Legs-Feet'
    WHOLE_BODY_TAG = 'Whole-Body'

    Ids = [NONE_ID, HEAD_ID, HEAD_CHEST_ID, HEAD_LEFT_ARM_ID, HEAD_LEFT_ARM_HAND_ID, HEAD_RIGHT_ARM_ID,
           HEAD_RIGHT_ARM_HAND_ID, HEAD_ARMS_ID, HEAD_ARMS_HANDS_ID, CENTER_ID, CENTER_HIPS_ID, CENTER_LEFT_LEG_ID,
           CENTER_LEFT_LEG_FOOT_ID, CENTER_RIGHT_LEG_ID, CENTER_RIGHT_LEG_FOOT_ID, CENTER_LEGS_ID, CENTER_LEGS_FEET_ID,
           WHOLE_BODY_ID]

    Tags = [NONE_TAG, HEAD_TAG, HEAD_CHEST_TAG, HEAD_LEFT_ARM_TAG, HEAD_LEFT_ARM_HAND_TAG, HEAD_RIGHT_ARM_TAG,
            HEAD_RIGHT_ARM_HAND_TAG, HEAD_ARMS_TAG, HEAD_ARMS_HANDS_TAG, CENTER_TAG, CENTER_HIPS_TAG,
            CENTER_LEFT_LEG_TAG, CENTER_LEFT_LEG_FOOT_TAG, CENTER_RIGHT_LEG_TAG, CENTER_RIGHT_LEG_FOOT_TAG,
            CENTER_LEGS_TAG, CENTER_LEGS_FEET_TAG, WHOLE_BODY_TAG]

