

class BodyJointsCatalog(object):

    NONE_ID = 0
    HEAD_ID = 1
    CHEST_ID = 2
    LEFT_SHOULDER_ID = 3
    RIGHT_SHOULDER_ID = 4
    LEFT_ELBOW_ID = 5
    RIGHT_ELBOW_ID = 6
    LEFT_WRIST_ID = 7
    RIGHT_WRIST_ID = 8
    LEFT_HAND_METACARPUS_ID = 9
    RIGHT_HAND_METACARPUS_ID = 10
    LEFT_FINGER_ID = 11
    RIGHT_FINGER_ID = 12
    CENTER_ID = 13
    LEFT_HIP_ID = 14
    RIGHT_HIP_ID = 15
    LEFT_KNEE_ID = 16
    RIGHT_KNEE_ID = 17
    LEFT_ANKLE_ID = 18
    RIGHT_ANKLE_ID = 19
    LEFT_FOOT_METACARPUS_ID = 20
    RIGHT_FOOT_METACARPUS_ID = 21
    LEFT_TOE_ID = 22
    RIGHT_TOE_ID = 23

    NONE_TAG = 'None'
    HEAD_TAG = 'Head'
    CHEST_TAG = 'Chest'
    LEFT_SHOULDER_TAG = 'Left shoulder'
    RIGHT_SHOULDER_TAG = 'Right shoulder'
    LEFT_ELBOW_TAG = 'Left elbow'
    RIGHT_ELBOW_TAG = 'Right elbow'
    LEFT_WRIST_TAG = 'Left wrist'
    RIGHT_WRIST_TAG = 'Right wrist'
    LEFT_HAND_METACARPUS_TAG = 'Left hand metacarpus'
    RIGHT_HAND_METACARPUS_TAG = 'Right hand metacarpus'
    LEFT_FINGER_TAG = 'Left finger'
    RIGHT_FINGER_TAG = 'Right finger'
    CENTER_TAG = 'Center'
    LEFT_HIP_TAG = 'Left hip'
    RIGHT_HIP_TAG = 'Right hip'
    LEFT_KNEE_TAG = 'Left knee'
    RIGHT_KNEE_TAG = 'Right knee'
    LEFT_ANKLE_TAG = 'Left ankle'
    RIGHT_ANKLE_TAG = 'Right ankle'
    LEFT_FOOT_METACARPUS_TAG = 'Left foot metacarpus'
    RIGHT_FOOT_METACARPUS_TAG = 'Right foot metacarpus'
    LEFT_TOE_TAG = 'Left toe'
    RIGHT_TOE_TAG = 'Right toe'

    Ids = [NONE_ID, HEAD_ID, CHEST_ID, LEFT_SHOULDER_ID, RIGHT_SHOULDER_ID, LEFT_ELBOW_ID, RIGHT_ELBOW_ID,
           LEFT_WRIST_ID, RIGHT_WRIST_ID, LEFT_HAND_METACARPUS_ID, RIGHT_HAND_METACARPUS_ID, LEFT_FINGER_ID,
           RIGHT_FINGER_ID, CENTER_ID, LEFT_HIP_ID, RIGHT_HIP_ID, LEFT_KNEE_ID,  RIGHT_KNEE_ID, LEFT_ANKLE_ID,
           RIGHT_ANKLE_ID, LEFT_FOOT_METACARPUS_ID, RIGHT_FOOT_METACARPUS_ID, LEFT_TOE_ID, RIGHT_TOE_ID]

    Tags = [NONE_TAG, HEAD_TAG, CHEST_TAG, LEFT_SHOULDER_TAG, RIGHT_SHOULDER_TAG, LEFT_ELBOW_TAG, RIGHT_ELBOW_TAG,
            LEFT_WRIST_TAG, RIGHT_WRIST_TAG, LEFT_HAND_METACARPUS_TAG, RIGHT_HAND_METACARPUS_TAG, LEFT_FINGER_TAG,
            RIGHT_FINGER_TAG, CENTER_TAG, LEFT_HIP_TAG, RIGHT_HIP_TAG, LEFT_KNEE_TAG,  RIGHT_KNEE_TAG, LEFT_ANKLE_TAG,
            RIGHT_ANKLE_TAG, LEFT_FOOT_METACARPUS_TAG, RIGHT_FOOT_METACARPUS_TAG, LEFT_TOE_TAG, RIGHT_TOE_TAG]
